import "./globals.css";
import '@/assets/styles/index.scss';
import "sweetalert2/src/sweetalert2.scss";
import Layout from '@/component/hoc/Layout';
import 'react-toastify/dist/ReactToastify.css';
import NextTopLoader from "nextjs-toploader";
import { Suspense } from "react";

export const metadata = {
  title: 'Gymnastify',
  description: 'Generated by create next app',
  manifest: "/manifest.json"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
      </head> */}
      <body>
      <NextTopLoader />
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  )
}
